name: SonarQube
description: Scans every pull request
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  SONAR_URL:
    description: 'Url for sonar server'
    required: true
  SONAR_PROJECT_KEY:
    description: 'Target project key'
    required: true
  SONAR_PROJECT_NAME:
    description: 'Target project name'
    required: true
  SONAR_TOKEN:
    description: 'Sonar bot token'
    required: true
  GITHUB_REPOSITORY:
    description: 'Target repository'
    required: true
  GITHUB_ACCESS_TOKEN:
    description: 'Put this as a secret in the target repository'
    required: true
  GITHUB_PULL_REQUEST:
    description: 'Pull Request ID repository'
    required: true
branding:
  icon: 'umbrella'
  color: 'gray-dark'
